service: spacex-launch-service
frameworkVersion: '>=3.0.0 <4.0.0'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 256
  timeout: 30
  stage: dev

  environment:
    TABLE_NAME: ${self:provider.stage}-SpaceXLaunches
    AWS_ACCESS_KEY_ID: dummy
    AWS_SECRET_ACCESS_KEY: dummy

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:000000000000:table/${self:provider.stage}-SpaceXLaunches

functions:
  fetchLaunches:
    handler: lambdafn.handler.main
    events:
      - schedule:
          rate: rate(6 hours)
          enabled: true
      - http:
          path: run
          method: get
          cors: true

  getLaunches:
    handler: lambdafn.get.handler
    events:
      - http:
          path: launches
          method: get
          cors: true

resources:
  Resources:
    SpaceXLaunchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-SpaceXLaunches
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Project
            Value: SpaceX

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    installPath: .dynamodb
